EU_emissions_ntb
faktaoklimatu/data-analysis pull request #11
Opened 2023-01-31 13:08 UTC by matejpiro

Project 2_EU emissions graph

2023-02-10 15:20 UTC, jankrcal commented on notebooks/EU_emissions.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #2.    df_new = pd.DataFrame()
</pre><p>Wouldn't the same be obtained by the following, instead of the for-cycle?</p><p> </p><pre class="ql-syntax" spellcheck="false">dw_new = df.emis.filter(items=states_dict.values(), axis="index")
</pre>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/11/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2023-02-10 15:20 UTC, jankrcal commented on notebooks/EU_emissions.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #2.    df_merged.rename(columns = {f'{year}_x':f'{year}_emis', f'{year}_y':f'{year}_popul'}, inplace = True)
</pre><p>You can avoid this renaming by providing .merge() above with an argument suffixes=("_emis", "_popul"), see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/11/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2023-02-10 15:20 UTC, jankrcal commented on notebooks/EU_emissions.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    # Jak hodit Německo do levýho horního rohu? a musí to tak bejt?
</pre><p>Leave this for later, consult it with Katka. This is super-easy to do in Illustrator, I guess, but we need to ask.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/11/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2023-02-13 09:13 UTC, matejpiro commented on notebooks/EU_emissions.ipynb
> +{
<p>Ah. and I was so proud of my f" string renaming... :) </p><p>solved</p>

2023-02-16 10:16 UTC, matejpiro commented on notebooks/EU_emissions.ipynb
> +{
<p>not by .filter (cause this method "does not filter a dataframe on its contents. The filter is applied to the labels of the index." ) but I applied another solution. For cycle is out now. </p>

2023-02-16 12:06 UTC, jankrcal commented on notebooks/EU_emissions.ipynb
> +{
You would need to set 'geo' as the index. But your solution works as well, thanks!

2023-02-27 08:31 UTC, jankrcal commented on notebooks/EU_emissions.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #7.                   'České Republika':'CZ',
</pre><p> </p><p>same here: fix typo</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/11/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2023-02-27 08:31 UTC, jankrcal commented on notebooks/EU_emissions.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #11.                   'Špenělsko':'ES',
</pre><p> </p><p>fix typo: Španělsko</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/11/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2023-02-27 08:31 UTC, jankrcal commented on notebooks/EU_emissions.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #10.        df_merged['em_na_oby'] = (df_merged[f'{year}_emis'] * 1000000) / df_merged[f'{year}_popul']
</pre><p>Please use English for column names (such as 'em_per_capita' and 'country' one line below)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/11/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2023-02-27 08:32 UTC, jankrcal requested changes
Please fix 3 minor comments. Apart from that, it looks good, thanks!

2023-02-27 09:25 UTC, matejpiro commented on notebooks/EU_emissions.ipynb
> +{
<p>Oh sure. The first is latin, but I see to point. Fixed. </p>

2023-02-27 09:30 UTC, matejpiro commented
Ready for review

2023-02-27 09:39 UTC, jankrcal approved these changes

2023-03-09 15:14 UTC, merged