Add files via upload
faktaoklimatu/data-analysis pull request #4
Opened 2022-09-18 17:39 UTC by matejpiro

2022-09-19 07:34 UTC, jankrcal requested changes
Thanks for the work!

Here's a first round of comments :)

Apart from those comments, could you please delete Gl_Fok_pokus1.ipynb as part of this PR and rename this file to something meaningful w.r.t. naming conventions here? (such as "regional-emissions-by-category.ipynb")

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "# tady ne všemu rozumim... ale sem sto to zkopírovat:-P\n",
I'd use wedgeprops' width to make a donut. Here's an example of nested donut plot:
https://matplotlib.org/stable/gallery/pie_and_polar_charts/nested_pie.html

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "# TA ČÍSLA se mírně liší od těch v tabulce od Honzy. Proč? Eurostat aktualizoval data? Nebo tam něco počítám blbě? \n"
Minor inconsistencies are to be expected, Eurostat is adjusting past data quite often.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "_, ax = plt.subplots() # tomu podtržítku na začátku nerozumim.\n",
plt.subplots() returns two variables, naming one of them as "_" is a convention that you don't care about it - you don't use it in the code.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "Import modulů"
We use English in this repo. I don't mind if you stick with Czech in this pull request but please use English in all comments, eventually.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df = df.rename(columns={'geo\\\\time': 'geo_time'}) # povšimni si těch dvou lomítek v \"geo\\\\time\""
I don't think this is needed - you refer to this column exactly once, why not just use geo\\\\time in that place?

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df = df.rename(columns={2018: '2018'}) # nějak přehazuju asi datatyp? sloupce. jinak to dělá binec. "
This is weird but I'd need to debug to see what's going on. Let's keep this for later.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df = df.rename(columns={2018: '2018'}) # nějak přehazuju asi datatyp? sloupce. jinak to dělá binec. "
I'd like to have the year and the country as a constant up in the notebook so that you can easily change that later on when you update the graph.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df4 = df3.query(\"src_crf in ('CRF2', 'CRF1A2', 'CRF1A1','CRF1A4','CRF5','CRF3','CRF1A3','CRF1D1A' )\") # \"query in\" je dobrý umět\n"
Similarly, I'd like to have a config dictionary somewhere up in the notebook that specifies
 - the partitioning in the pie chart (i.e. the CRF codes that you use),
 - the labels for the corresponding wedges.

This way, the configuration would be separate from the code that generates the plot based on the configuration. When you need the chart for another country with different configuration, the code stays and you only change the configuration.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df4.loc[len(df.index)] = C # přidej řádek a vlož do něj hodnotu \"C\". nevim co dělá to \"len\"\n",
I don't think this manipulation with the dataframe is needed and it also results in ugly code, IMO :)

Since the graph is simple, using only a few datapoints, you can crate a few simple python lists that you pass into ax.pie():
 - a list of values that you extract from the dataframe,
 - a list of labels that you already have.
You don't need to inject all these values into Pandas.

That would be simpler and more straightforward code.

btw. `len(df.index)` is returning the number of rows `df` currently has. In general `len(x)` returns the length of the array/list/dictionary `x`. In combination with .loc[], you're basically appending a new row.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df4 = df4.rename(index={63130: 'CRF1A3_CRF1D1A'}) # přejmenuj index pro nový řádek \"63130\"\n"
Hard coding an index value 63130 is particularly ugly :) This code breaks whenever the dataset changes :)

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df4 = df4.drop(index = 'CRF1A3') # proč je tady jen jedno \"=\"?\n",
one '=' is used because index is a named argument for the drop() function. See, e.g., https://treyhunner.com/2018/04/keyword-arguments-in-python/

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "# bacha ať to opravdu sedí - eukod - label. Nebylo by lepší udělat to jinak? .. třeba už proto, že tady je nutný aby to mělo přesný počet řádků?\n",
Yeah, this is what I'm hinting towards. I'd rather have a configuration in the form:

wedges = [
 {codes: ['CRF2'],
  label: "Energetika"},
 ...
 {codes: ['CRF1A3', 'CRF1D1A']
  label: "Doprava (včetně letecké)"},
 {label: "Jiné"},
]

and based on the codes (or lack of codes for the remainder wedge) extract the values.

2022-09-19 07:34 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df4 = df4.sort_values(by= ['2018'], ascending=False)\n",
Sorting can be done manually in the configuration (anyway, we sometimes may want to deviate from the sorted order, for instance to achieve consistency of the same plot over time) so I don't think this justifies injecting all the data into Pandas.

2022-09-25 11:03 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "import eurostat"
Sure. Done.

2022-09-25 11:07 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "Import modulů"
ok. I will.

2022-09-25 11:20 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df = df.rename(columns={'geo\\\\time': 'geo_time'}) # povšimni si těch dvou lomítek v \"geo\\\\time\""
I tried in the first place. But an error occured. So I ended up with renaming the collumn. 
![bug_geo_time](https://user-images.githubusercontent.com/60359089/192140811-9322d708-0dad-48b4-9c93-3ceafb8b245b.png)

2022-09-25 11:58 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df = df.rename(columns={2018: '2018'}) # nějak přehazuju asi datatyp? sloupce. jinak to dělá binec. "
Sure. Makes sence. Fixed.

2022-09-25 12:01 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df = df.rename(columns={2018: '2018'}) # nějak přehazuju asi datatyp? sloupce. jinak to dělá binec. "
As I set the constants (year, state), this problem dissapeard. So I deleted this part of a code.

2022-09-26 12:12 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df = df.rename(columns={'geo\\\\time': 'geo_time'}) # povšimni si těch dvou lomítek v \"geo\\\\time\""
Ah, you're probably right, see a similar issue [1]. Please update the comment above to mention that Pandas query() does not allow backslash in column names.

[1] https://stackoverflow.com/questions/69619280/pandas-eval-with-backslash-in-column-names

2022-09-26 12:13 UTC, jankrcal reviewed
A few reactions... good progress.

Please say it explicitly when this pull request is ready for another round of review.

2022-09-26 12:58 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df4 = df4.rename(index={63130: 'CRF1A3_CRF1D1A'}) # přejmenuj index pro nový řádek \"63130\"\n"
True. That was very ugly. 
New solution via:
df.append(new_df) 
df = df.rename(index={0: 'CRF1A3_CRF1D1A'})

2022-09-26 13:01 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +    "df4 = df4.sort_values(by= ['2018'], ascending=False)\n",
Ok. Sorting is an easy thing to change. No need to bother us now I think.

2022-10-07 14:53 UTC, jankrcal commented on notebooks/Gl_Fok_pokus2.ipynb
> +{
<p>Can you please delete this file from the pull request?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2022-10-07 14:53 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    df = df.rename(columns={'geo\\time': 'geo_time'}) # povšimni si těch dvou lomítek v "geo\\time" - Honza bez přejmenování ale 'geo\\time' hází chybu.
</pre><p>This column should actually be named 'geo', the 'time' part refers to the other columns.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2022-10-07 14:53 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    df4 = df3.query("src_crf in ('CRF2', 'CRF1A2', 'CRF1A1','CRF1A4','CRF5','CRF3','CRF1A3','CRF1D1A' )") 
</pre><p>I'd like this query to be generated from <code>label_dict_1</code>  and <code>label_dict_2</code>. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2022-10-07 14:53 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #3.    C = A+B
</pre><p>In the same way, I'd like all such computations to be done without manual code, based on <code>label_dict_1</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2022-10-07 14:53 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #3.    df4 = df4.rename(index={0: 'CRF1A3_CRF1D1A'}) # přejmenuj index
</pre><p>Not sure why that index should be 0 when you use append?</p><p>Why not replace both lines by&nbsp;<code>df.loc['CRF1A3_CRF1D1A'] = [C]</code>?</p><p> </p><p>Either way, not sure if this manipulation of df is needed, we can discuss next week.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2022-10-07 14:53 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #10.    ax.pie(df_outer[2018], radius=1, labels = df_outer.index, counterclock=False, startangle=90, 
</pre><p>Can you try plot only part of the outer circle (as we do in the original graph)?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='53'/>

2022-10-08 18:18 UTC, matejpiro commented on notebooks/Gl_Fok_pokus2.ipynb
> +{
deleted... I hope.

2022-10-13 08:44 UTC, matejpiro commented on notebooks/regional-emissions-by-category.ipynb
> +{
ok. renamed.

2022-11-11 07:42 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<p>(add_sum a count_sum navrhuju nahradit kódem níže)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2022-11-11 07:42 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<p>Tady děláš dvakrát velmi podobnou věc různým kódem. Ještě výše děláš velmi podobnou věc ohledně součtů. Navrhuju všechno spojit.</p><p> </p><p>Tedy navrhuju něco jako (netestoval jsem):</p><pre class="ql-syntax" spellcheck="false"># Generic function that computes the value for a reminder.
def add_sums_and_reminder(definition, total_code, df):
    total_sum = 0
    for wedge_def in definition:
&nbsp; &nbsp;     if 'sum' in wedge_def:
&nbsp; &nbsp;         sum = get_sum(wedge_def['sum'], df)
&nbsp; &nbsp;         df.loc[wedge_def['code'], YEAR] = sum
            total_sum += sum
&nbsp; &nbsp; &nbsp; &nbsp; elif 'reminder' in wedge_def:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; diff = get_value(total_code, df) - total_sum
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; df.loc[wedge_def['code'], YEAR] = diff # přidá nový řádek ke stávajímu df

# Call that function on the main set of wedges and and all the breakdown wedges.
add_sums_and_reminder(definition, 'TOTX4_MEMONIA', df)
for wedge_def in definition:
&nbsp; &nbsp; if 'breakdown' in wedge_def:
&nbsp; &nbsp;    add_sums_and_reminder(wedge_def, wedge_def['code'], df)

</pre>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2022-11-11 07:42 UTC, jankrcal commented on notebooks/regional-emissions-by-category.ipynb
> +{
<p>drobnost: Tento blok bych spojil s tím výše. Je to úplně stejná struktura, tak to za mě pomůže čitelnosti, když se kódy i labely definují na stejném místě.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/faktaoklimatu/data-analysis/pull/4/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='21'/>

2022-11-11 18:23 UTC, matejpiro commented on notebooks/regional-emissions-by-category.ipynb
> +{
<p>Tady byla potřeba udělat drobná změna. </p><p>Jinak to jede:)</p><p> </p><pre class="ql-syntax" spellcheck="false">for wedge_def in definition:
    if 'breakdown' in wedge_def:
        add_sums_and_reminder(wedge_def['breakdown'], wedge_def['code'], df2)
</pre><p> </p>

2022-12-07 09:06 UTC, jankrcal requested changes
Thanks, really good progress!

Another round of comments (I hope the final one before approving the PR)

2022-12-07 09:06 UTC, jankrcal commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +    _add_sums_and_reminder(definition, 'TOTX4_MEMONIA', {}, df)
'TOTX4_MEMONIA' literal is repeated to 3 times: please turn it into a constant defined at the top.

2022-12-07 09:06 UTC, jankrcal commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +def _create_relative_outer_df(inner_chart_structure, outer_chart_structure, df):
This computes the same as `outer_perc_dict`. Options:
 A) get rid of `outer_perc_dict` computation and collect values directly in `_create_plot_lists`
 B) get rid of `_create_relative_outer_df` and pass in `outer_perc_dict` as values that get plotted.

I lean towards A) but both is fine.

2022-12-09 08:44 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +    _add_sums_and_reminder(definition, 'TOTX4_MEMONIA', {}, df)
fixed

2022-12-09 08:47 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +        df.loc[wedge_code, 'value'] = wedge_value  # přidá nový řádek ke stávajímu df
ok, deleted.

2022-12-09 09:31 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +    sum = 0
if it is optional, i would stick to my current code.

2022-12-09 10:49 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +def _create_relative_outer_df(inner_chart_structure, outer_chart_structure, df):
Oh, I see.
I prefer B cause is more understandable for me. 
But than we will have to have this lines of code:     _outer_perc_dict = {}_
                                                                                 __compute_values(definition, df, outer_perc_dict)_
 both in _draw_plot and in create_plot cause both computes with "outer_perc_dict" ... is that ok?

2022-12-09 11:09 UTC, jankrcal commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +    sum = 0
Sure :)

2022-12-09 12:51 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +def _create_relative_outer_df(inner_chart_structure, outer_chart_structure, df):
I would say thats the solution, but "TypeError: 'numpy.ndarray' object is not callable" occurs... Didnt figure out why yet...

2022-12-09 15:20 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_state_definitions.py
> +definitions = {
dobře, hotovo.

2022-12-12 09:25 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +def _create_relative_outer_df(inner_chart_structure, outer_chart_structure, df):
Eh bože, já sem neskutečný trotl... Už to funguje:)

2022-12-12 12:23 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +        "inner_chart_structure": [], "outer_chart_structure": [],
I see. The codes define the structure... And the structure is the key element here. If its not a big deal for you, I stick to the current naming.

2022-12-12 12:28 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +def _get_value(key, df):  # získej hodnotu. Zadej klíč a df
sure

2022-12-12 12:41 UTC, matejpiro commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +    df = df[["src_crf", year]]  # jen kod odvětví a rok
sure

2022-12-13 06:41 UTC, jankrcal approved these changes
Great work, thanks!

In a previous version, you had definitions for SK, CZ and EU. Would you mind adding notebooks for CZ and EU as well? (I don't care if it's in this PR or in a follow-up)

2022-12-13 06:41 UTC, jankrcal commented on notebooks/regional_emissions_by_category_lib/emission_plots.py
> +    """Define paramethers to draw the plot"""
typo: parameters

2022-12-14 13:06 UTC, merged